% Task 6 - Robustness Validation
% Increase the sprung mass by 25% and rerun the road test suite.

clear;
clc;
close all;

modelName = "quarter_car_model_and_road_test";

% Tuned suspension parameters from Task 5
Ms = 300 * 1.25;   % Sprung mass increased by 25%
Mu = 40;

ms = Ms;
mu = Mu;

Ks = 21000;
Cs = 1200;
Kt = 180000;
Ct = 100;

% Pass/fail performance criteria
requirements = struct( ...
    "RMSAcceleration", 3.0, ...
    "PeakAcceleration", 8.0, ...
    "SuspensionTravel", 0.080, ...
    "TireDeflection", 0.050);

% Road cases
roadCases = struct( ...
    "Name",        {"speedBump",  "pothole",   "roughRoad"}, ...
    "Scenario",    {"Speed_Bump", "Pothole",   ""}, ...
    "SwitchValue", {1,            1,           0}, ...
    "StopTime",    {5,            5,           5});

modelFile = modelName + ".slx";

if ~isfile(modelFile)
    error('Model file "%s" was not found in the current folder.', modelFile);
end

resultsFolder = fullfile(pwd, "results");

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

% Put parameters in the base workspace before opening the model
assignin("base", "Ms", Ms);
assignin("base", "Mu", Mu);
assignin("base", "ms", ms);
assignin("base", "mu", mu);
assignin("base", "Ks", Ks);
assignin("base", "Cs", Cs);
assignin("base", "Kt", Kt);
assignin("base", "Ct", Ct);

load_system(modelName);

signalEditorPath = modelName + "/Signal Editor";
manualSwitchPath = modelName + "/Manual Switch";

resultsTable = table();

for k = 1:numel(roadCases)

    roadName = roadCases(k).Name;

    fprintf('Running Task 6 simulation %d/%d: %s\n', ...
        k, numel(roadCases), roadName);

    in = Simulink.SimulationInput(modelName);

    % Tuned suspension with 25% payload increase
    in = in.setVariable("Ms", Ms);
    in = in.setVariable("Mu", Mu);
    in = in.setVariable("ms", ms);
    in = in.setVariable("mu", mu);
    in = in.setVariable("Ks", Ks);
    in = in.setVariable("Cs", Cs);
    in = in.setVariable("Kt", Kt);
    in = in.setVariable("Ct", Ct);

    % Select road case
    in = in.setBlockParameter(manualSwitchPath, ...
        "CurrentSetting", num2str(roadCases(k).SwitchValue));

    if roadCases(k).Scenario ~= ""
        in = in.setBlockParameter(signalEditorPath, ...
            "ActiveScenario", roadCases(k).Scenario);
    end

    in = in.setModelParameter( ...
        "StopTime", num2str(roadCases(k).StopTime), ...
        "ReturnWorkspaceOutputs", "on", ...
        "SaveOutput", "on", ...
        "OutputSaveName", "yout", ...
        "SaveFormat", "Dataset");

    try
        simOut = sim(in);

        task3Input.logsout = simOut.get("yout");

        metrics = scoreSuspension(task3Input, roadName);

        comfortPass = ...
            metrics.rmsAccel <= requirements.RMSAcceleration && ...
            metrics.peakAccel <= requirements.PeakAcceleration;

        travelPass = ...
            metrics.maxTravel <= requirements.SuspensionTravel;

        tirePass = ...
            metrics.maxTireDefl <= requirements.TireDeflection;

        overallPass = comfortPass && travelPass && tirePass;

        row = table( ...
            string(metrics.road), ...
            metrics.rmsAccel, ...
            metrics.peakAccel, ...
            metrics.maxTravel, ...
            metrics.maxTireDefl, ...
            comfortPass, ...
            travelPass, ...
            tirePass, ...
            overallPass, ...
            "Completed", ...
            'VariableNames', { ...
            'Road', ...
            'RMSAcceleration_mps2', ...
            'PeakAcceleration_mps2', ...
            'MaxSuspensionTravel_m', ...
            'MaxTireDeflection_m', ...
            'ComfortPass', ...
            'TravelPass', ...
            'TirePass', ...
            'OverallPass', ...
            'SimulationStatus'});

    catch ME
        warning('Simulation failed for %s: %s', roadName, ME.message);

        row = table( ...
            string(roadName), ...
            NaN, ...
            NaN, ...
            NaN, ...
            NaN, ...
            false, ...
            false, ...
            false, ...
            false, ...
            "FAILED: " + string(ME.message), ...
            'VariableNames', { ...
            'Road', ...
            'RMSAcceleration_mps2', ...
            'PeakAcceleration_mps2', ...
            'MaxSuspensionTravel_m', ...
            'MaxTireDeflection_m', ...
            'ComfortPass', ...
            'TravelPass', ...
            'TirePass', ...
            'OverallPass', ...
            'SimulationStatus'});
    end

    resultsTable = [resultsTable; row]; %#ok<AGROW>
end

% Calculate worst-case metrics and pass rate
worstRMSAcceleration = max(resultsTable.RMSAcceleration_mps2);
worstPeakAcceleration = max(resultsTable.PeakAcceleration_mps2);
worstSuspensionTravel = max(resultsTable.MaxSuspensionTravel_m);
worstTireDeflection = max(resultsTable.MaxTireDeflection_m);

passedCases = nnz(resultsTable.OverallPass);
totalCases = height(resultsTable);
passRate = 100 * passedCases / totalCases;

robustnessSummary = table( ...
    Ms, ...
    Ks, ...
    Cs, ...
    worstRMSAcceleration, ...
    worstPeakAcceleration, ...
    worstSuspensionTravel, ...
    worstTireDeflection, ...
    passedCases, ...
    totalCases, ...
    passRate, ...
    'VariableNames', { ...
    'SprungMass_kg', ...
    'Ks_Npm', ...
    'Cs_NsPm', ...
    'WorstRMSAcceleration_mps2', ...
    'WorstPeakAcceleration_mps2', ...
    'WorstSuspensionTravel_m', ...
    'WorstTireDeflection_m', ...
    'PassedCases', ...
    'TotalCases', ...
    'PassRate_Percent'});

fprintf('\nTask 6 Road-Case Results:\n');
disp(resultsTable);

fprintf('\nTask 6 Robustness Summary:\n');
disp(robustnessSummary);

writetable(resultsTable, ...
    fullfile(resultsFolder, "task6_road_case_results.csv"));

writetable(robustnessSummary, ...
    fullfile(resultsFolder, "task6_robustness_summary.csv"));

fprintf('Road cases passed: %d of %d\n', passedCases, totalCases);
fprintf('Pass rate: %.1f%%\n', passRate);